imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
   

framework:
    #esi:             ~
    translator:      { fallback:  en }
       #"%locale%"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  en 
        #"%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        optimus_instance: "%optimus_instance%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

parameters:
    optimus_instance: Sant Cugat
    optimus_endpoint: "http://optimusdss.epu.ntua.gr:8890/sparql"
    optimus_graph: "http://optimus_santcugat"

    OPTIMUS_SENSORS: 0

    optimus_actionPlans: 8

    action_plan_1:
        name: "Scheduling and management of the occupancy"
        status: 0
        type: 1
        description: "Reduction of the building energy consumption by changing the location of building occupants, so as to use the minimum number of thermal zones and turn off the heating/cooling system in the empty zones."

    action_plan_2:
        name: "Scheduling the set-point temperature (Thermal Comfort Validation and Adaptive Comfort Concept)"
        status: 0
        type: 2
        description: "Support of the energy manager in adjusting the temperature set-point, taking into consideration thermal comfort parameters. The target is to optimize energy use, while maintaining comfort levels in accepted ranges (using the Predicted Mean Vote - PMV - index)."

    action_plan_3:
        name: "Optimum Start/Stop of the Heating/Cooling System"
        status: 0
        type: 4
        description: "Optimization of the boost time of the heating/cooling system taking into account the forecasting of the outdoor air temperature and the occupancy of the building."

    action_plan_4:
        name: "PV Maintenance "
        status: 0
        type: 5
        description: "Detection of the need for maintenance of the PV system and communication with the user with an alert prompting for appropriate maintenance actions; identification of abnormalities and possible problems can be facilitated."

    action_plan_5:
        name: "Scheduling of the Sale/Consumption of the RES Electricity Produced"
        status: 0
        type: 6
        description: "Optimization of selling/self-consumption of electricity produced by a PV system considering different scenarios of energy market (green strategy, finance strategy, intermediate strategy, peak strategy, load factor strategy)."

    action_plan_6:
        name: "Scheduling of the Energy Flows"
        status: 0
        type: 7
        description: "Efficient Management of Energy Flows linking buildings (e.g. Savona campus thermal and electrical demands), RES production (e.g. PV and CSP production) and dispatchable sources (e.g. storage)."

    action_plan_7:
        name: "Scheduling of the Energy Flows"
        status: 0
        type: 7
        description: "Efficient Management of Energy Flows linking buildings (e.g. Savona campus thermal and electrical demands), RES production (e.g. PV and CSP production) and dispatchable sources (e.g. storage)."

    action_plan_8:
        name: "Management of air side Economizer"
        status: 0
        type: 8
        description: "Management of air side Economizer."

    energy_demand_threshold_percentage: 5
    daily_penalty_energy_threshold: 100000

    pvm_num_panels: 40
    pvm_panels_surface_area: 80
    pvm_a_coefficient: 1
    pvm_ta_coefficient: 1
