optimus_optimus:
    resource: "@OptimusOptimusBundle/Resources/config/routing.yml"
    prefix:   /

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /init
        permanent: true
